// <auto-generated Note="Disable CodeMaid sorting." />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DocWeb
{
    class TaskSchedulerParam
    {

        public string Description { get; set; }

        #region 操作

        public string ExePath { get; set; }

        public string ExeArgs { get; set; }

        #endregion

        #region 触发器

        public bool Enable { get; set; } = true;
        
        /// <summary>
        /// 格式 <![CDATA[YYYY-MM-DDTHH:MM:SS(+-)HH:MM]]>，后面是时区
        /// <br>https://learn.microsoft.com/en-us/windows/win32/taskschd/trigger-startboundary</br>
        /// </summary>
        public string StartTime { get; set; } = DateTime.Now.ToString(TimePattern);

        /// <summary>
        /// 格式 <![CDATA[P<days>DT<hours>H<minutes>M<seconds>S]]>，最小1分，最大31天
        /// <br>https://learn.microsoft.com/en-us/windows/win32/taskschd/repetitionpattern-interval</br>
        /// </summary>
        
        public string Interval { get; set; } = "P1DT0H0M0S";

        #endregion

        public const string TimePattern = "yyyy-M-dTHH:mm:ss";
    }
}
